### ISSUE TITLE
提案コンポーネントの「サポート」（投票の意味）まわりの用語を変えたい

### ISSUE THREAD

**Issue by kken78** [codeforjapan/decidim-cfj#196]
## 改善詳細 / Details of Improvement
- いわゆる「投票」を行う際に、現在の日本語訳では「サポート」になっている
　汎用的な用語（この提案をサポートしたい！という意味では、正しいとも言える）だが、補足説明が必要だと思う
- 関連する用語の訳も揃えたい（なお、管理ダッシュボード側の用語も揃える必要が出てくる）
- 配布された投票数を使い切っても「十分なサポート（持ち票）があります」となる

なお、
- 別のボタンが「支持する」（元はEndorcement）になっていて紛らわしい
- ただし、管理ダッシュボードで非表示にすることができるため、管理者側がそのことを理解できていれば問題はないが、すべてのコンポーネントで出現有無を設定できるものであり、訳語を修正する必要がありそう

## スクリーンショットなど / Screenshot
- 当初の画面（サポートを３票とした場合）
<img width="1235" alt="スクリーンショット 2021-03-22 10 13 17" src="https://user-images.githubusercontent.com/35302518/111929233-1a707700-8af9-11eb-9ffa-b6a8a64b7587.png">

- ２票つかった場合　※「十分なサポートがあります」←本当は「あと１票です」の方がいいのかもしれないが、ややこしそう
<img width="1227" alt="スクリーンショット 2021-03-22 10 13 38" src="https://user-images.githubusercontent.com/35302518/111929265-34aa5500-8af9-11eb-880d-ed253cfc5e97.png">

- サポートを全て使い切った場合　※「十分なサポートがあります」が残っている
<img width="1221" alt="スクリーンショット 2021-03-22 10 13 46" src="https://user-images.githubusercontent.com/35302518/111929274-3b38cc80-8af9-11eb-9d91-c0ced1b09d41.png">

- 個別の提案ページでの「サポート」と「支持」が紛らわしい
<img width="1230" alt="スクリーンショット 2021-03-22 10 31 35" src="https://user-images.githubusercontent.com/35302518/111929502-d9c52d80-8af9-11eb-9343-c1264e50e009.png">

## 期待する見せ方・挙動 / Expected behavior
【現在の表現】
サポートは以下のルールに従います：
・最大N件の提案をサポートできます。
・異なる提案に最低1のサポートを配布する必要があります。十分なサポートがあります。

【提案する表現】 
サポートしたい提案を選んでください：
・最大N件の提案に「サポート」マークをつけることができます。
・どれか1つにサポートしてください。
（・あとM件の提案にサポートできます　←可能であれば）

## 対象インスタンス / Instances

- 全て

**Comment by takahashim** [comment]
参考情報として、voting_rules関連の日本語メッセージは以下になります。

```yaml
        voting_rules:
          can_accumulate_supports_beyond_threshold:
            description: 各提案は %{limit} 以上のサポートを蓄積できます
          minimum_votes_per_user:
            description: 異なる提案に最低 %{votes} のサポートを配布する必要があります。
            given_enough_votes: 十分なサポートがあります。
            supports_remaining: サポートを考慮するためには、あと %{remaining_votes} 件の提案をサポートする必要があります。
          proposal_limit:
            description: 最大 %{limit} 件の提案を作成できます。
          threshold_per_proposal:
            description: 検証されるためには、 %{limit} のサポートに到達する必要があります
          title: 'サポートは以下のルールに従います:'
          vote_limit:
            description: 最大 %{limit} 件の提案をサポートできます。
            left: 残り
            votes: サポート
```
https://github.com/decidim/decidim/blob/8e9f7997222ded9dfc66874b50236ef5c0c1e9c3/decidim-proposals/config/locales/ja.yml#L797-L812

対応する英語メッセージは以下になります。

```yaml
        voting_rules:
          can_accumulate_supports_beyond_threshold:
            description: Each proposal can accumulate more than %{limit} supports
          minimum_votes_per_user:
            description: You must distribute a minimum of %{votes} supports among different proposals.
            given_enough_votes: You've given enough supports.
            supports_remaining: You have to support %{remaining_votes} more proposals for your supports to be taken into account.
          proposal_limit:
            description: You can create up to %{limit} proposals.
          threshold_per_proposal:
            description: In order to be validated proposals need to reach %{limit} supports
          title: 'Supports are subject to the following rules:'
          vote_limit:
            description: You can support up to %{limit} proposals.
            left: Remaining
            votes: Supports
```

https://github.com/decidim/decidim/blob/8e9f7997222ded9dfc66874b50236ef5c0c1e9c3/decidim-proposals/config/locales/en.yml#L838-L853
