### ISSUE TITLE
コメントへのリアクションボタンが分かり難い

### ISSUE THREAD

**Issue by tomoaki-n** [codeforjapan/decidim-cfj#41]
## 改善詳細 / Details of Improvement
- コメントへのリアクションボタンが分かり難い

## スクリーンショットなど / Screenshot
![IMG_2064](https://user-images.githubusercontent.com/22102102/97069461-98445b00-160b-11eb-968d-dd403d70db8a.PNG)

## 期待する見せ方・挙動 / Expected behavior
- ポジティブが∧、ネガティブが∨になっているのを👍とｑ（すみません絵が出ず）等に変える

## 対象インスタンス / Instances

- 全て
- ○○市

**Comment by mcyph** [comment]
ちょっとしたmonkey patchなんですけど、下のCSSを`app/assets/stylesheets/decidim.scss`に加えたら、こうなります：

```css
// Replace ^ v icons with thumbs to make their action more clear
.comment__votes--up {
  svg {
    display: none;
  }
}
.comment__votes--up:before {
  content: "👍"
}
.comment__votes--down {
  svg {
    display: none;
  }
}
.comment__votes--down:before {
  content: "👎"
}
```

![image](https://user-images.githubusercontent.com/20507948/97079548-9d6fcd00-1640-11eb-9c3a-01ec7e367905.png)

完璧ではないですが、`chevron-bottom`や`chevron-up`は`decidim-core/app/assets/images/decidim/icons.svg`ファイルからレファレンスされて、たくさんの`*.erb`ファイルにハードコードしているみたいなので、かなり大きいrevisionになれる可能性があると思います。その代わりに、絵文字を使わずに👍👎イメージ使ったり、例の`icons.svg`も直接変更したりできると思います。
