### ISSUE TITLE
ログインバタンを中央揃えにする

### ISSUE THREAD

**Issue by mcyph** [codeforjapan/decidim-cfj#46]
## 改善詳細 / Details of Improvement

自分だけじゃないかは分かりませんけど、ログインボタンが左揃えであるとレイアウトが少し調和していないような気がします。

## スクリーンショットなど / Screenshot

![image](https://user-images.githubusercontent.com/20507948/97079016-4cf67080-163c-11eb-90fa-9a7ae19f7cc9.png)

## 期待する見せ方・挙動 / Expected behavior

`/app/assets/stylesheets/decidim.css`にこの中央揃えにするCSS入れたらこの問題が解決されると思います。

```css
.button--social{
  padding: 0;
}
.button--social__icon,
.button--social__text{
  text-align: center;
  margin: 0;
}
```

そうすると中心のポジションになります：

![image](https://user-images.githubusercontent.com/20507948/97078964-fa1cb900-163b-11eb-8d41-e7985ab8aeeb.png)

## 動作環境・ブラウザ / Environment
Linux Ubuntu 18.04 LTS
Firefox 82.0
