### ISSUE TITLE
最後のアクティビティを改行したい

### ISSUE THREAD

**Issue by isaozz** [codeforjapan/decidim-cfj#73]
## 改善詳細 / Details of Improvement
- 最後のアクティビティの「タイトル」と「説明」の間を改行したい
- 可能ならばという程度です。クリティカルなものではありません。

## スクリーンショットなど / Screenshot
![最後のアクティビティ](https://user-images.githubusercontent.com/40754081/97402005-2df62800-1935-11eb-82f2-e29a04117411.png)

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 対象インスタンス / Instances

- 全て
- 加古川市

**Comment by takahashim** [comment]
この件ですが、v0.23.5にアップグレードしてDecidimAwesomeを導入すると、CSSが設定できるようになります。
管理画面から「Decidim awesome」→「独自スタイル」→「styles の詳細設定」の設定で以下のようなCSSをカスタムスタイルとして設定することで表示を変えられるようでした。

```css
div.card--activity .card__content .card__header a.card__link {
  display: block;
}
```
